version: '3.9'

services:

  server:
    image: 'challenge-1.0.0.jar'
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=challenge
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=challenge
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

  flyway:
    image: flyway/flyway:6.4.1-alpine
    environment:
     - FLYWAY_EDITION=community
    command: -url=jdbc:postgresql://db:5432/postgres -schemas=public -user=postgres -password=challenge -connectRetries=10 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql